# Generated by Django 4.2 on 2023-04-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_rename_created_at_filesection_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='catalog',
            new_name='catalog_id',
        ),
    ]
