# Generated by Django 4.2 on 2023-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_alter_catalog_id_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
