# Generated by Django 4.2 on 2023-05-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='catalog_id',
        ),
        migrations.AddField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
