# Generated by Django 4.2 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0010_file_file_delete_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
