# Generated by Django 4.2 on 2023-05-10 11:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0011_folder_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 10, 11, 49, 43, 147652, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
